### ISSUE TITLE
Create auto-documentation

### ISSUE THREAD

**Issue by AboudyKreidieh** [AboudyKreidieh/truck-code#3]
**Due date**: December 17, 2018

**Tasks**:
- [ ] merge documentation branch into master
- [ ] Add the html files in a docs/ folder
- [ ] Format the documentation to auto-update whenever code is push to master.
