### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by AboudyKreidieh** [AboudyKreidieh/truck-code#4]
**Due date**: December 17, 2018

**Tasks**:
- [ ] Add a section about general code structure, with the picture I've created before.
- [ ] Brief description of each software component.
- [ ] Reference to documentation
